<?php
$isvegan = array(
    "acetate",
    "acetylated hydrogenated lard glyceride",
    "acetylated lanolin",
    "acetylated lanolin alcohol",
    "acetylated lanolin ricinoleate",
    "acetylated tallow",
    "acid",
    "acidophilus milk",
    "adrenaline",
    "adrenals of cattle",
    "adrenals of hogs",
    "adrenals of sheep",
    "afterbirth",
    "alanine",
    "albumen",
    "albumin",
    "alcloxa",
    "aldioxa",
    "aliphatic alcohol",
    "allantoin",
    "alligator",
    "alligator skin",
    "alpha-hydroxy acids",
    "amerachol",
    "amerchol l101",
    "aminiuccinate acid",
    "amino acids",
    "aminosuccinate acid",
    "ammonium caseinate",
    "ammonium hydrolyzed protein",
    "amniotic fluid",
    "ampd isoteric hydrolyzed animal protein",
    "amylase",
    "anchovies",
    "anchovy",
    "angora",
    "animal bones",
    "animal collagen amino acids",
    "animal fat",
    "animal fats and oils",
    "animal hair",
    "animal keratin amino acids",
    "animal oil",
    "animal placenta",
    "animal protein derivative",
    "animal tissue extract",
    "arachidonic acid",
    "arachidyl proprionate",
    "aspartic acid",
    "aspic",
    "astrakhan",
    "back bacon",
    "back fat",
    "bacon",
    "bass",
    "batyl alcohol",
    "batyl isostearate",
    "bear",
    "bee pollen",
    "bee products",
    "beef",
    "beef heart",
    "beef liver",
    "beef tongue",
    "beepollen",
    "beeswax",
    "beeswax honeycomb",
    "belly bacon",
    "benzyltrimonium hydrolyzed animal protein",
    "biotin vitamin h vitamin b factor",
    "bison",
    "blood",
    "blood plasma fractionation",
    "blood tongue",
    "boar bristles",
    "boiled ham",
    "bone ash",
    "bone char",
    "bone char(coal)/boneblack",
    "bone charcoal",
    "bone earth",
    "bone meal",
    "bone phosphate",
    "bone soup",
    "bone/bonemeal",
    "boneblack",
    "bonito",
    "bovine serum albumin",
    "brain extract",
    "bratwurst",
    "brawn",
    "breakfast bacon",
    "bresaola",
    "bristle",
    "bruehwurst",
    "buffalo",
    "buffalo milk",
    "bushmeat",
    "butter",
    "butter fat",
    "butter solids",
    "buttermilk",
    "buttermilk powder",
    "c30-46 piscine oil",
    "calamari",
    "calciferol",
    "calciferool",
    "calcium caseinate",
    "calf liver",
    "calfskin",
    "calfskin extract",
    "camel milk",
    "canadian bacon",
    "cantharides tincture",
    "capiz",
    "capryl betaine",
    "caprylamine oxide",
    "caprylic acid",
    "caprylic triglyceride",
    "carbamide",
    "caribou",
    "carmine",
    "carmine cochineal carminic acid",
    "carmine/carminic acid",
    "carmine: cochineal. carminic acid",
    "carminic",
    "carminic acid",
    "carotene provitamin a beta carotene",
    "carp",
    "casein",
    "casein caseinate sodium caseinate",
    "caseinate",
    "caseinogen",
    "cashmere",
    "castor castoreum",
    "catfish",
    "catgut",
    "catharidin",
    "caviar(e)",
    "cera flava",
    "cerebrosides",
    "certain additives",
    "ceteth-02",
    "ceteth-1",
    "ceteth-10",
    "ceteth-2",
    "ceteth-30",
    "ceteth-4",
    "ceteth-6",
    "cetyl alcohol",
    "cetyl lactate",
    "cetyl myristate",
    "cetyl palmitate",
    "chamois",
    "cheese",
    "chicken",
    "chicken breast",
    "chicken liver",
    "chicken loaf",
    "chipped ham",
    "chitin",
    "chitosan",
    "cholecalciferol",
    "cholesterol",
    "choline bitartrate",
    "chondroitin",
    "chopped ham",
    "chorizo",
    "chymotrypsin",
    "civet",
    "clarified butter",
    "clotted cream",
    "cochineal",
    "cod",
    "cod liver oil",
    "cold cuts",
    "coleth-24",
    "collagen",
    "collagen hydrolysate",
    "colors dyes",
    "condensed milk",
    "confectioners glaze",
    "cooked ham",
    "cooked meats",
    "coral",
    "corned beef",
    "cornish game hen",
    "cortico steroid",
    "corticosteroid",
    "cortisone",
    "cortisone corticosteroid",
    "cortisone: see cortico steroid.",
    "cotechino",
    "cottage cheese",
    "crab",
    "crabmeat",
    "crawfish",
    "crayfish",
    "cream",
    "crustacean shellfish",
    "curds",
    "custard",
    "cysteine, l-form",
    "cystine",
    "dark meat",
    "dashi",
    "dea-oleth-10 phosphate",
    "deer",
    "deer meat",
    "delactosed whey",
    "deli meats",
    "demineralized whey",
    "deoxyribonucleic acid",
    "desamido animal collagen",
    "desamidocollagen",
    "devon",
    "dexpanthenol",
    "dicapryloyl cystine",
    "diethylene tricaseinamide",
    "diglycerides",
    "dihydrocholesterol",
    "dihydrocholesterol octyledecanoate",
    "dihydrocholeth-15",
    "dihydrocholeth-30",
    "dihydrogenated tallow benzylmoniumchloride",
    "dihydrogenated tallow methylamine",
    "dihydrogenated tallow phthalate",
    "dihydroxyethyl tallow amine oxide",
    "dimethyl hydrogenated tallowamine",
    "dimethyl stearamine",
    "dimethyl tallowamine",
    "disodium hydrogenatedtallowglutamate",
    "disodium tallamido mea-sulfosuccinate",
    "disodium tallowaminodipropionate",
    "ditallowdimonium chloride",
    "dna",
    "down",
    "dried buttermilk",
    "dried egg yolk",
    "dry milk solids",
    "dry whole milk",
    "duck",
    "duck bacon",
    "duck liver",
    "duodenum substances",
    "dutch loaf",
    "dyes",
    "e120",
    "e441",
    "e542",
    "e904",
    "e913",
    "edible bone phosphate",
    "egg",
    "egg albumen",
    "egg albumen/albumin",
    "egg oil",
    "egg powder",
    "egg protein",
    "egg whites",
    "egg yolk",
    "egg yolk extract",
    "egg yolks",
    "eggs",
    "elastin",
    "elk bacon",
    "embryo extract",
    "emu",
    "emu oil",
    "epiderm oil r",
    "ergisterol",
    "ergocalciferol",
    "ergosterol",
    "estradiol",
    "estradiol benzoate",
    "estrogen",
    "estrogen estradiol",
    "estrogen/estradiol",
    "estrone",
    "ethyl ester of hydrolyzed animal protein",
    "ethyl morrhuatelipineate",
    "ethylarachidonate",
    "ethylene dehydrogenated tallowamide",
    "evaporated milk",
    "ewe milk",
    "fat-free milk",
    "fat-free yogurt",
    "fats",
    "fatty acids",
    "fd and c colors",
    "feathers",
    "felt",
    "fermented camel milk",
    "fermented cream",
    "fermented milk",
    "fish",
    "fish glycerides",
    "fish liver",
    "fish liver oil",
    "fish livers",
    "fish oil",
    "fish sauce",
    "fish scales",
    "fishsauce",
    "fletan oil",
    "fur",
    "gel",
    "gelatin",
    "gelatin gel",
    "gelatin(e)",
    "gelbwurst",
    "ghee",
    "gizzards",
    "glucosamine",
    "glucose tyrosinase",
    "glucuronic acid",
    "glutamic acid",
    "glycerides",
    "glycerin glycerol",
    "glycerol",
    "glyceryl lanolate",
    "glyceryls",
    "glycogen",
    "glycreth-26",
    "goat",
    "goat cheese",
    "goat milk",
    "goose",
    "goose insulating feathers",
    "goose liver",
    "ground beef",
    "grouse",
    "guanine",
    "guanine pearl essence",
    "guanine/pearl essence",
    "guinea hen",
    "gypsy bacon",
    "haddock",
    "hair from hogs",
    "halibut",
    "ham",
    "ham and cheese loaf",
    "head cheese",
    "heavy cream",
    "heptylundecanol",
    "hide",
    "hide glue",
    "homogenized milk",
    "honey",
    "honeycomb",
    "horse",
    "horse hair",
    "horseflesh",
    "horsehair",
    "hot dog",
    "human placental protein",
    "human umbilical extract",
    "hyaluronic acid",
    "hydrlyzed human placental protein",
    "hydrocortisone",
    "hydrogenated animal glyceride",
    "hydrogenated ditallow amine",
    "hydrogenated honey",
    "hydrogenated laneth-20",
    "hydrogenated laneth-25",
    "hydrogenated laneth-5",
    "hydrogenated lanolin",
    "hydrogenated lanolin alcohol",
    "hydrogenated lard glyceride",
    "hydrogenated shark-liver oil",
    "hydrogenated tallow acid",
    "hydrogenated tallow betaine",
    "hydrogenated tallow glyceride",
    "hydrolyzed animal elastin",
    "hydrolyzed animal keratin",
    "hydrolyzed animal protein",
    "hydrolyzed casein",
    "hydrolyzed elastin",
    "hydrolyzed keratin",
    "hydrolyzed milk protein",
    "hydrolyzed silk",
    "hydroxylated lanolin",
    "ice cream",
    "imidazolidinyl urea",
    "insulin",
    "iron caseinate",
    "isinglass",
    "isobutylated lanolin",
    "isopropyl lanolate",
    "isopropyl myristate",
    "isopropyl tallowatelsopropyl lanolate",
    "isopropylpalmitate",
    "isostearic hydrolyzed animal protein",
    "isostearoyl hydrolyzed animal protein",
    "jagdwurst",
    "jowl",
    "kangaroo",
    "katsuobushi (okaka)",
    "keratin",
    "keratinamino acids",
    "l-cysteine",
    "l-form",
    "l-form: see cysteine.",
    "l-lactic acid",
    "lacotse-reduced milk",
    "lactalbumin",
    "lactic yeasts",
    "lacticacid",
    "lactoferrin",
    "lactoglobulin",
    "lactose",
    "lactose-free milk",
    "lactulose",
    "lamb",
    "lamb bacon",
    "laneth",
    "laneth-10",
    "laneth-11",
    "laneth-12",
    "laneth-13",
    "laneth-14",
    "laneth-15",
    "laneth-16",
    "laneth-17",
    "laneth-18",
    "laneth-19",
    "laneth-20",
    "laneth-21",
    "laneth-22",
    "laneth-23",
    "laneth-24",
    "laneth-25",
    "laneth-26",
    "laneth-27",
    "laneth-28",
    "laneth-29",
    "laneth-30",
    "laneth-31",
    "laneth-32",
    "laneth-33",
    "laneth-34",
    "laneth-35",
    "laneth-36",
    "laneth-37",
    "laneth-38",
    "laneth-39",
    "laneth-40",
    "laneth-5",
    "laneth-6",
    "laneth-7",
    "laneth-8",
    "laneth-9",
    "laneth-9 acetate",
    "laneth10 acetate",
    "lanogene",
    "lanoinamidedea",
    "lanolin",
    "lanolin acid",
    "lanolin acid: see lanolin.",
    "lanolin alcohol",
    "lanolin alcohols",
    "lanolin alcohols: see lanolin.",
    "lanolin lanolin acids wool fat wool wax",
    "lanolin linoleate",
    "lanolin oil",
    "lanolin ricinoleate",
    "lanolin wax",
    "lanolin(e)",
    "lanolin: lanolin acid",
    "lanosterol",
    "lanosterol: see lanolin.",
    "lanosterols",
    "lard",
    "lard glyceride",
    "lauroyl hydrolyzed animal protein",
    "leather",
    "leather suede calfskin sheepskinalligator skin other types of skin",
    "lecithin cholinebitartrate",
    "leucine",
    "linoleic acid",
    "lipase",
    "lipids",
    "lipoids lipids",
    "liver",
    "liver extract",
    "liverwurst",
    "lobster",
    "low fat milk",
    "low fat yogurt",
    "lunasponge",
    "luncehon loaf",
    "lunch meats",
    "luncheon meats",
    "lysine",
    "mackerel",
    "magnesium caseinate",
    "malted milk",
    "mammarian extract",
    "marine oil",
    "marrow soup",
    "mayonnaise",
    "mea-hydrolyzed animal protein",
    "meat",
    "meat loaf",
    "meatball",
    "mechanically separated chicken",
    "methionine",
    "mettwurst",
    "milk",
    "milk chocolate",
    "milk derivative",
    "milk of mammals",
    "milk protein",
    "milk skin",
    "milk sugar",
    "milkfat",
    "milkpowder",
    "minced beef",
    "minced meat",
    "mink oil",
    "minkamidopropyl diethylamine",
    "mohair",
    "molluscan shellfish",
    "monkfish",
    "mono and di-glycerides",
    "monoglycerides glycerides",
    "monoglycerides glycerides (see glycerin)",
    "moose",
    "mortadella",
    "mossbunker oil",
    "mullet",
    "muscle extract",
    "musk",
    "musk (oil)",
    "musk ambrette",
    "mussel",
    "mussels",
    "mutton",
    "myristal ether sulfate",
    "myristate acid",
    "myristic acid",
    "myristoyl hydrolyzed animal protein",
    "myristyl",
    "myristyls",
    "natural butter flavor",
    "natural flavorings",
    "natural red 4",
    "natural sources",
    "neck",
    "nonfat milk",
    "note:",
    "nougat",
    "nucleicacids",
    "ocenol",
    "octopus",
    "octyl dodecanol",
    "oils",
    "oleamidopropyl dimethylamine hydrolyzed animal protein",
    "oleic acid",
    "oleoic oil",
    "oleostearine",
    "oleoyl hydrolyzed animal protein",
    "oleths",
    "oleyl arachidate",
    "oleyl betatine",
    "oleyl imidazoline",
    "oleyl lanolate",
    "oleyl myristate",
    "oleyl oleate",
    "oleyl stearate",
    "oleylalcohol ocenol",
    "oleylimidazoline",
    "omega-3 fatty acids",
    "opossum",
    "organ meat",
    "organ meats",
    "organs",
    "ostrich",
    "ovalbumin",
    "ovarian extract",
    "ox bile",
    "oxgall",
    "oyster",
    "palmitamide",
    "palmitamine",
    "palmitate",
    "palmitic acid",
    "palmitoyl hydrolyzed milk protein",
    "palmitoyl hydrolyzedanimal protein",
    "pancetta",
    "panthenol dexpanthenol vitamin b-complex factor provitamin b-5",
    "panthenyl",
    "paracasein",
    "partridge",
    "pasteurized milk",
    "pearl",
    "pearl essence",
    "pentahydrosqualene",
    "pepsin",
    "perhydrosqualene",
    "pharmaceutical glaze",
    "pheasant",
    "picnic shoulder",
    "pigskin extract",
    "placenta",
    "placenta placenta polypeptides protein afterbirth",
    "placenta polypeptides protein",
    "placental enzymes",
    "placental extract",
    "placental protein",
    "plaice",
    "pogy oil",
    "pollock",
    "poltethylene cetyl ether",
    "polyglycerol",
    "polyglyceryl-2lanolin alcohol ether",
    "polypeptides",
    "polypeptides protein",
    "polysorbates",
    "polytetylene glycerol/glycol/peg",
    "porcine pancreas",
    "pork",
    "pork fat",
    "pork roll",
    "potassium caseinate",
    "potassium tallowate",
    "potassium undecylenoyl hydrolyzed animal protein",
    "poultry",
    "ppg-12-peg-50 lanolin",
    "ppg-2,-5, -10. -20, -30 lanolinalcohol ethers",
    "ppg-30 lanolin ether",
    "prawn",
    "pregnenolone acetate",
    "pristane",
    "progesterone",
    "propolis",
    "prosciutto",
    "provitamin a",
    "provitamin b-5",
    "provitamin d-2",
    "purcelline oil syn",
    "quail",
    "quaternium 27",
    "rabbit",
    "red meat",
    "reduced fat milk",
    "reduced fat yogurt",
    "rennet",
    "rennet casein",
    "rennet rennin",
    "rennin",
    "resinous glaze",
    "reticulin",
    "retinol",
    "ribonucleic acid",
    "rna ribonucleic acid",
    "roast beef",
    "roast pork",
    "roe",
    "royal jelly",
    "sable",
    "sable brushes",
    "saccharide hydrolysate",
    "saccharide isomerate",
    "salami",
    "salceson",
    "salmon",
    "sardine",
    "sausage",
    "sausages",
    "scallop",
    "scallops",
    "sea sponge",
    "sea turtle oil",
    "seasponge",
    "serum albumin",
    "serum proteins",
    "shark liver oil",
    "shark-liver oil",
    "sheep milk",
    "sheepskin",
    "shellac",
    "shellac resinous glaze",
    "shellac wax",
    "shoulder",
    "shrimp",
    "shrimph",
    "side bacon",
    "silk",
    "silk amino acids",
    "silk powder",
    "silk silk powder",
    "skim milk",
    "slab bacon",
    "sliced meats",
    "smoked ham",
    "snail",
    "snails",
    "snake",
    "snapper",
    "sodium / tea-lauroyl hydrolyzed animal protein",
    "sodium / tea-undecylenoyl hydrolyzed animal protein",
    "sodium caseinate",
    "sodium coco-hydrolyzed animal protein",
    "sodium soya hydrolyzed animal protein",
    "sodium tallow sulfate",
    "sodium tallowate",
    "sodium undecylenate",
    "sodiumsteroyl lactylate",
    "soluble  collagen",
    "sour cream",
    "sour milk",
    "sour milk solids",
    "soured milk",
    "soya hydroxyethyl imidazoline",
    "sperm oil",
    "sperm whale intestines",
    "spermaceti",
    "spermaceticetyl palmitate sperm oil",
    "spleen extract",
    "sponge (luna and sea)",
    "squab",
    "squalane",
    "squalene",
    "squid",
    "squirrel",
    "steak",
    "stearamide",
    "stearamine",
    "stearamine oxide",
    "stearates",
    "stearic acid",
    "stearic hydrazide",
    "stearin",
    "stearone",
    "stearoxytrimethylsilane",
    "stearoyl lactylic acid",
    "stearyl acetate",
    "stearyl alcohol sterols",
    "stearyl betaine",
    "stearyl caprylate",
    "stearyl citrate",
    "stearyl glycyrrhetinate",
    "stearyl heptanoate",
    "stearyl imidazoline",
    "stearyl octanoate",
    "stearyl stearate",
    "stearyldimethyl amine",
    "steroids sterols",
    "sterols",
    "stewing steak",
    "stilton",
    "streaky bacon",
    "suede",
    "sweet dairy whey",
    "sweet whey",
    "sweetbreads",
    "sweetened condensed milk",
    "swordfish",
    "tallow",
    "tallow acid",
    "tallow amide",
    "tallow amine",
    "tallow amine oxide",
    "tallow fatty alcohol",
    "tallow glycerides",
    "tallow hydroxyethal imidazoline",
    "tallow imidazoline",
    "tallow tallow fatty alcohol stearic acid",
    "tallow trimonium chloride - tallow",
    "tallowamidopropylamine oxide",
    "talloweth-6",
    "tallowmide dea and mea",
    "tallowmidopropyl hydroxysultaine",
    "tallowminopropylamine",
    "tallowmphoacete",
    "tea-abietoyl hydrolyzedanimal protein",
    "tea-coco hydrolyzed animal protein",
    "tea-lauroyl animal collagen amino acids",
    "tea-lauroyl animal keratin amino acids",
    "tea-myristol hydrolyzed animal protein",
    "tea-undecylenoyl hydrolyzed animal protein",
    "testicular extract",
    "threonine",
    "thuringian sausage",
    "tilapia",
    "tongue",
    "triethonium hydrolyzed animal protein ethosulfate",
    "trilaneth-4phosphate",
    "tripe",
    "triterpene alcohols",
    "trout",
    "trypsin",
    "tuna",
    "turkey",
    "turkey bacon",
    "turkey breast",
    "turtle",
    "turtle oil",
    "tyrosine",
    "un-homogenized milk",
    "urea",
    "urea carbamide",
    "uric acid",
    "uric acid from cows",
    "uricacid",
    "urine",
    "veal",
    "veal loaf",
    "venison",
    "vitamin a",
    "vitamin b-complex factor",
    "vitamin d ergocalciferol vitamin d",
    "vitamin d3",
    "vitamin h",
    "vitaminb",
    "vitaminb factor",
    "volaise",
    "whey",
    "whey powder",
    "whey protein",
    "whipped cream",
    "whipped topping",
    "white meat",
    "whole milk",
    "whole milk yogurt",
    "wild boar",
    "wild meat",
    "wool",
    "wool fat",
    "wool wax",
    "wool wax alcohols",
    "yoghurt",
    "yogurt",
    "zinc caseinate",
    "zinc hydrolyzed animal protein",

    // german
    "acetat",
    "acetyliertes hydriertes schmalzglycerid",
    "acetyliertes lanolin",
    "acetylierter lanolinalkohol",
    "acetyliertes lanolin-ricinoleat",
    "acetylierter talg",
    "säure",
    "acidophilus-milch",
    "adrenalin",
    "nebennieren von rindern",
    "nebennieren von schweinen",
    "nebennieren von schafen",
    "nachgeburt",
    "alanin",
    "eiweiß",
    "aliphatischer alkohol",
    "alligatorhaut",
    "alpha-hydroxysäuren",
    "ambra", 
    "ambergris",
    "amerchol",
    "aminiuccinat-säure",
    "aminosäuren",
    "aminosuccinat-säure",
    "ammoniumkaseinat",
    "ammoniumhydrolysiertes protein",
    "fruchtwasser",
    "ampd isoterisches hydrolisiertes tierisches eiweiß",
    "anchovis",
    "tierknochen",
    "tierische kollagen-aminosäuren",
    "tierisches fett",
    "tierische fette und öle",
    "tierische haare",
    "tierische keratin-aminosäuren",
    "tierisches öl",
    "tierische plazenta",
    "tierische proteinderivate",
    "tierischer gewebeextrakt",
    "arachidonsäure",
    "arachidylproprionat",
    "asparaginsäure",
    "sülze",
    "rückenspeck",
    "speck",
    "batylalkohol",
    "batylisostearat",
    "bär",
    "bienenpollen",
    "bienenprodukte",
    "rindfleisch",
    "rinderherz",
    "rinderleber",
    "rinderzunge",
    "bienenwachs",
    "bienenwachs-wabe",
    "bauchspeck",
    "benzyltrimonium hydrolysiertes tierisches eiweiß",
    "biotin-vitamin-h-vitamin-b-faktor",
    "blut",
    "blutplasmafraktionierung",
    "blutzunge",
    "wildschweinborsten",
    "gekochter schinken",
    "knochenasche",
    "knochenkohle",
    "knochenkohle/knochenschwarz",
    "knochenerde",
    "knochenmehl",
    "knochenphosphat",
    "knochensuppe",
    "knochen/knochenmehl",
    "knochenschwarz",
    "rinderserumalbumin",
    "gehirn-extrakt",
    "frühstücksspeck",
    "borste",
    "büffel",
    "büffelmilch",
    "buschfleisch",
    "butterfett",
    "butterfeststoffe",
    "buttermilch",
    "buttermilchpulver",
    "c30-46-piscinöl",
    "kalziumkaseinat",
    "kalbsleber",
    "kalbsleder", "kalbshäute",
    "kalbshäutextrakt",
    "kamelmilch",
    "kanadischer speck",
    "canthariden-tinktur",
    "kapiz",
    "caprylbetain",
    "caprylaminoxid",
    "caprylsäure",
    "capryltriglycerid",
    "harnstoff",
    "karibu",
    "karmin",
    "karmin-cochenille-karminsäure", "karmin/karmin",
    "karmin/karminsäure",
    "karmin: cochenille. karminsäure",
    "karminsäure",
    "karotin: provitamin a beta-karotin",
    "karpfen",
    "kasein",
    "kasein-kaseinat-natrium-kaseinat",
    "kaseinat",
    "kaseinogen",
    "kaschmir",
    "rizinus", 
    "castoreum",
    "kastor",
    "wels",
    "welsdarm",
    "kaviar(e)",
    "cerebroside",
    "bestimmte zusatzstoffe",
    "cetylalkohol",
    "cetyllactat",
    "cetylmyristat",
    "cetylpalmitat",
    "gämse",
    "käse",
    "huhn",
    "hühnerbrust",
    "hühnerleber",
    "hühnerbrot",
    "gehackter schinken",
    "cholesterin",
    "cholinbitartrat",
    "zibet",
    "butterschmalz",
    "geronnene sahne",
    "cochenille",
    "kabeljau",
    "lebertran",
    "aufschnitt",
    "kollagen",
    "kollagen-hydrolysat",
    "farbstoffe",
    "kondensierte milch",
    "konditorglasur",
    "gekochtes fleisch",
    "koralle",
    "kornisches wildhuhn",
    "kortikosteroid",
    "kortison",
    "kortison-kortikosteroid",
    "kortison: siehe kortikosteroid",
    "hüttenkäse",
    "krabbe",
    "krabbenfleisch",
    "languste",
    "flusskrebs",
    "sahne",
    "krustentier", "schalentier",
    "quark",
    "pudding",
    "cystein, l-form",
    "cystin",
    "dunkles fleisch",
    "dea-oleth-10-phosphat",
    "hirsch",
    "hirschfleisch",
    "delaktosierte molke",
    "delikatessenfleisch",
    "demineralisierte molke",
    "desoxyribonukleinsäure",
    "desamidiertes tierisches kollagen",
    "desamidokollagen",
    "dicapryloyl-cystin",
    "diethylentrikaseinamid",
    "diglyceride",
    "dihydrocholesterin",
    "dihydrocholesterol-octyledecanoat",
    "dihydriertes talgbenzylmoniumchlorid",
    "dihydriertes talg-methylamin",
    "dihydriertes talgphthalat",
    "dihydroxyethyltalg-aminoxid",
    "dimethylhydriertes talgamin",
    "dimethylstearamin",
    "dimethyl-tallowamin",
    "dinatriumhydriertes talglichtglutamat",
    "dinatrium-tallamido-mea-sulfosuccinat",
    "dinatriumtallowaminodipropionat",
    "ditallowdimoniumchlorid",
    "daunen",
    "getrocknete buttermilch",
    "getrocknetes eigelb",
    "milchtrockenmasse",
    "trockene vollmilch",
    "ente",
    "entenspeck",
    "entenleber",
    "zwölffingerdarmstoffe",
    "holländischer laib",
    "essbares knochenphosphat",
    "ei",
    "eialbumin",
    "eialbumin/albumin",
    "ei-öl",
    "eipulver",
    "eiprotein",
    "eigelb",
    "eigelb-extrakt",
    "eier",
    "elchspeck",
    "embryo-extrakt",
    "emu-öl",
    "östradiolbenzoat",
    "östrogen",
    "östrogen-östradiol",
    "östrogen/östradiol",
    "östron",
    "ethylester von hydrolysiertem tierischem eiweiß",
    "morrhuatelipineat-ethyl",
    "ethylarachidonat",
    "ethylen-dehydriertes tallowamid",
    "evaporierte milch",
    "schafsmilch",
    "fettfreie milch",
    "fettfreier joghurt",
    "fette",
    "fettsäuren",
    "farbstoffe fd und c",
    "federn",
    "filz",
    "fermentierte kamelmilch",
    "fermentierte sahne",
    "fermentierte milch",
    "fisch",
    "fischglyceride",
    "fischleber",
    "fischleberöl",
    "fischöl",
    "fischsauce",
    "fischschuppen",
    "fletanöl",
    "pelz",
    "gelatine",
    "gelatine-gel",
    "gelatine(n)",
    "saumagen",
    "glucosamin",
    "glukose-tyrosinase",
    "glucuronsäure",
    "glutaminsäure",
    "glyceride",
    "glycerin-glycerol",
    "glycerin",
    "glyceryl-lanolat",
    "glykogen",
    "ziege",
    "ziegenkäse",
    "ziegenmilch",
    "gans",
    "gänse-isolierfedern",
    "gänseleber",
    "rinderhackfleisch",
    "moorhuhn",
    "guanin",
    "guanin-perlen-essenz",
    "guanin/perlenessenz",
    "perlhuhn",
    "zigeunerspeck",
    "schellfisch",
    "haare von schweinen",
    "heilbutt",
    "schinken",
    "schinken-käse-laib",
    "kopfkäse",
    "schwere sahne",
    "haut",
    "hautleim",
    "homogenisierte milch",
    "honig",
    "honigwabe",
    "pferd",
    "pferdehaar",
    "pferdefleisch",
    "rosshaar",
    "menschliches plazenta-protein",
    "menschlicher nabelschnurextrakt",
    "hyaluronsäure",
    "hydrolisiertes menschliches plazenta-protein",
    "hydrocortison",
    "hydriertes tierisches glycerid",
    "hydriertes ditallow-amin",
    "hydrierter honig",
    "hydriertes lanolin-20",
    "hydriertes laneth-25",
    "hydriertes lanolin-5",
    "hydriertes lanolin",
    "hydrierter lanolinalkohol",
    "hydriertes schmalzglycerid",
    "hydriertes haifischleberöl",
    "hydrierte talgsäure",
    "hydrierter talg betain",
    "hydriertes talgglycerid",
    "hydrolisiertes tierisches elastin",
    "hydrolisiertes tierisches keratin",
    "hydrolisiertes tierisches eiweiß",
    "hydrolisiertes kasein",
    "hydrolisiertes elastin",
    "hydrolysiertes keratin",
    "hydrolysiertes milchprotein",
    "hydrolysierte seide",
    "hydroxyliertes lanolin",
    "eiscreme",
    "imidazolidinylharnstoff",
    "eisen-kaseinat",
    "isinglas",
    "isobutyliertes lanolin",
    "isopropyl-lanolat",
    "isopropylmyristat",
    "isopropyltallowatelsopropyl-lanolat",
    "isopropylpalmitat",
    "isostearisches hydrolysiertes tierisches eiweiß",
    "isostearoylhydrolysiertes tierisches eiweiß",
    "hängebacke",
    "känguru",
    "keratinaminosäuren",
    "l-cystein",
    "l-form: siehe cystein",
    "l-milchsäure",
    "laktose-reduzierte milch",
    "laktalbumin",
    "milchsäurehefen",
    "milchsäure",
    "laktoferrin",
    "laktoglobulin",
    "laktose",
    "laktosefreie milch",
    "laktulose",
    "lamm",
    "lammspeck",
    "laneth-9 acetat",
    "laneth-10-acetat",
    "lanolinsäure",
    "lanolinsäure: siehe lanolin",
    "lanolinalkohol",
    "lanolin-alkohole",
    "lanolin-alkohole: siehe lanolin",
    "lanolin lanolinsäuren wollfett wollwachs",
    "lanolin-linoleat",
    "lanolinöl",
    "lanolin-ricinoleat",
    "lanolinwachs",
    "lanolin: lanolinsäure",
    "lanosterin",
    "lanosterol: siehe lanolin",
    "lanosterole",
    "schmalz",
    "schmalzglycerid",
    "lauroylhydrolysiertes tierisches eiweiß",
    "leder",
    "leder, wildleder, kalbsleder, schafsleder, krokodilleder, andere hauttypen",
    "lecithin-cholinbitartrat",
    "leucin",
    "linolsäure",
    "lipide",
    "lipoide lipide",
    "leber",
    "leberextrakt",
    "leberwurst",
    "hummer",
    "fettarme milch",
    "fettarmer joghurt",
    "lunaschwamm",
    "luncehonbrot",
    "mittagsmahlzeiten",
    "lysin",
    "makrele",
    "magnesiumkaseinat",
    "malzmilch",
    "säugetierextrakt",
    "meeresöl",
    "marksuppe",
    "mea-hydrolysiertes tierisches eiweiß",
    "fleisch",
    "hackbraten",
    "frikadelle",
    "mechanisch abgetrenntes hühnerfleisch",
    "methionin",
    "milch",
    "milchschokolade",
    "milchderivat",
    "milch von säugetieren",
    "milcheiweiß",
    "milchhaut",
    "milchzucker",
    "milchfett",
    "milchpulver",
    "hackfleisch",
    "nerzöl",
    "nerzamidopropyl-diethylamin",
    "weichtiere",
    "seeteufel",
    "mono- und di-glyceride",
    "monoglyceride-glyceride",
    "monoglyceride-glyceride (siehe glycerin)",
    "elch",
    "moosbunkeröl",
    "meeräsche",
    "muskelextrakt",
    "moschus",
    "moschus (öl)",
    "moschus ambrette",
    "muschel",
    "muscheln",
    "hammel",
    "myristaläthersulfat",
    "myristat-säure",
    "myristinsäure",
    "myristoylhydrolysiertes tierisches eiweiß",
    "myristyle",
    "natürliches butteraroma",
    "natürliche aromastoffe",
    "natürliches rot 4",
    "natürliche quellen",
    "hals",
    "hinweis:",
    "nukleinsäuren",
    "öle",
    "oleamidopropyldimethylamin, hydrolysiertes tierisches eiweiß",
    "ölsäure",
    "ölsäureöl", "oleoöl",
    "oleostearin",
    "oleoylhydrolysiertes tierisches eiweiß",
    "olethen",
    "oleyl-arachidat",
    "oleylbetatin",
    "oleyl-imidazolin",
    "oleyl-lanolat",
    "oleylmyristat",
    "oleyl-oleat",
    "oleylstearat",
    "oleylalkohol ocenol",
    "oleylimidazolin",
    "omega-3-fettsäuren",
    "organfleisch",
    "organe",
    "strauß",
    "eierstockextrakt",
    "ochsengalle",
    "auster",
    "palmitamid",
    "palmitamin",
    "palmitat",
    "palmitinsäure",
    "palmitoylhydrolysiertes milchprotein",
    "palmitoylhydrolysiertes tierisches eiweiß",
    "panthenol dexpanthenol vitamin b-komplex faktor provitamin b-5",
    "parakasein",
    "rebhuhn",
    "pasteurisierte milch",
    "perle",
    "perlenessenz",
    "pentahydrosqualen",
    "perhydrosqualen",
    "pharmazeutische glasur",
    "fasan",
    "picknick-schulter",
    "schweineschwartenextrakt",
    "plazenta",
    "plazenta plazenta polypeptide protein nachgeburt",
    "plazenta-polypeptid-protein",
    "plazentale enzyme",
    "plazenta-extrakt",
    "plazenta-protein",
    "scholle",
    "pogy-öl",
    "seelachs",
    "poltethylen-cetyl-ether",
    "polyglycerin",
    "polyglyceryl-2lanolinalkoholether",
    "polypeptide",
    "polypeptid-protein",
    "polysorbate",
    "polytetylenglycerin/glykol/peg",
    "bauchspeicheldrüse vom schwein",
    "schweinefleisch",
    "schweinefett", 
     "schweinerolle",
    "kaliumkaseinat",
    "kaliumtallowat",
    "kaliumundecylenoylhydrolysiertes tierisches eiweiß",
    "geflügel",
    "ppg-12-peg-50-lanolin",
    "ppg-2,-5, -10, -20, -30 lanolinalkoholether",
    "ppg-30 lanolin-ether",
    "pregnenolonacetat",
    "pristan",
    "progesteron",
    "purcellinöl syn",
    "wachtel",
    "kaninchen",
    "rotes fleisch",
    "fettreduzierte milch",
    "fettreduzierter joghurt",
    "lab",
    "labkasein",
    "lab-lab",
    "harzhaltige glasur",
    "retikulin",
    "ribonukleinsäure",
    "rna-ribonukleinsäure",
    "rinderbraten",
    "schweinebraten",
    "rogen",
    "gelée royale",
    "zobel",
    "zobelpinsel",
    "saccharid-hydrolysat",
    "saccharid-isomerat",
    "lachs",
    "wurst",
    "würstchen",
    "jakobsmuschel",
    "jakobsmuscheln",
    "meeresschwamm",
    "meeresschildkrötenöl",
    "seeschwamm",
    "serumalbumin",
    "serum-proteine",
    "haifischleberöl",
    "schafsfell",
    "schellack",
    "schellack-harzglasur",
    "schellackwachs",
    "schulter",
    "seitenspeck",
    "seide",
    "seidenaminosäuren",
    "seidenpulver",
    "seide seidenpulver",
    "magermilch",
    "fleichspeck",
    "geräucherter schinken",
    "schnecke",
    "schnecken",
    "schlange",
    "schnapper",
    "natrium/tee-lauryl-hydrolysiertes tierisches eiweiß",
    "natrium/tee-undecylenoyl-hydrolysiertes tierisches eiweiß",
    "natriumkaseinat",
    "natrium-kokos-hydrolysiertes tierisches eiweiß",
    "natrium-soja-hydrolysiertes tierisches eiweiß",
    "natriumtallowsulfat",
    "natriumtallowat",
    "natriumundecylenat",
    "natriumsteroyllactylat",
    "lösliches kollagen",
    "saure sahne",
    "saure milch",
    "sauermilchfeststoffe",
    "dickmilch",
    "sauermilch",
    "soja-hydroxyethyl-imidazolin",
    "samenöl",
    "pottwal-därme",
    "spermaceticetylpalmitat-spermienöl",
    "milz-extrakt",
    "schwamm (luna und meer)",
    "täubchen",
    "squalan",
    "squalen",
    "tintenfisch",
    "eichhörnchen",
    "stearamid",
    "stearamin",
    "stearaminoxid",
    "stearate",
    "stearinsäure",
    "stearinsäurehydrazid",
    "stearon",
    "stearoxytrimethylsilan",
    "stearoyllactylsäure",
    "stearylacetat",
    "stearylalkoholsterole",
    "stearylbetain",
    "stearylcaprylat",
    "stearylzitrat",
    "stearyl-glycyrrhetinat",
    "stearylheptanoat",
    "stearyl-imidazolin",
    "stearyloctanoat",
    "stearylstearat",
    "stearyldimethylamin",
    "steroide sterole",
    "sterole",
    "schmorsteak",
    "durchwachsener speck",
    "wildleder",
    "süßmolke",
    "bries",
    "gezuckerte kondensmilch",
    "schwertfisch",
    "talg",
    "talgsäure",
    "talg-amid",
    "talg-amin",
    "talgaminoxid",
    "talgfettalkohol",
    "talgglyceride",
    "talg-hydroxyethal-imidazolin",
    "talg-imidazolin",
    "talg-fettalkohol-stearinsäure",
    "talgtrimoniumchlorid - talg",
    "talgamidopropylaminoxid",
    "talgeth-6",
    "talgmid dea und mea",
    "talgmidopropylhydroxysultain",
    "talgminopropylamin",
    "talgmophoacete",
    "tee-abtietoyl-hydrolysiertes tierisches eiweiß",
    "teekokos hydrolysiertes tierisches eiweiß",
    "tee-lauroyl tierische kollagen-aminosäuren",
    "tee-lauroyl tierische keratin-aminosäuren",
    "tee-myristol-hydrolysiertes tierisches eiweiß",
    "tee-undecylenoyl-hydrolysiertes tierisches eiweiß",
    "hodenextrakt",
    "threonin",
    "thüringische wurst",
    "zunge",
    "triethonium-hydrolysiertes tierisches eiweiß-ethosulfat",
    "trilaneth-4-phosphat",
    "kutteln",
    "triterpen-alkohole",
    "forelle",
    "thunfisch",
    "truthahn",
    "truthahnspeck",
    "putenbrust",
    "schildkröte",
    "schildkrötenöl",
    "tyrosin",
    "unhomogenisierte milch",
    "harnstoff-harnstoff",
    "harnsäure",
    "harnsäure von kühen",
    "urinsäure",
    "urin",
    "kalbfleisch",
    "kalbsbraten",
    "wildbret",
    "vitamin-b-komplex-faktor",
    "vitamin b",
    "vitamin-b-faktor",
    "molke",
    "molkenpulver",
    "molkenprotein",
    "schlagsahne",
    "schlagobers",
    "weißes fleisch",
    "vollmilch",
    "vollmilchjoghurt",
    "wildschwein",
    "wildfleisch",
    "wolle",
    "wollfett",
    "wollwachs",
    "wollwachs-alkohole",
    "joghurt",
    "zinkkaseinat",
    "zinkhydrolysiertes tierisches eiweiß",
    // french
    "ormeau",
    "acétate",
    "glycéride de saindoux hydrogéné acétylé",
    "lanoline acétylée",
    "alcool de lanoline acétylée",
    "ricinoléate de lanoline acétylée",
    "suif acétylé",
    "acide",
    "lait acidophilus",
    "adrénaline",
    "surrénales de bovins",
    "surrénales de porcs",
    "surrénales de moutons",
    "post-naissance",
    "albumine",
    "alcool aliphatique",
    "allantoïne",
    "peau d'alligator",
    "acides alpha-hydroxy",
    "ambre gris",
    "acide amino-uccinique",
    "acides aminés",
    "acide aminosuccinate",
    "caséinate d'ammonium",
    "protéine hydrolysée d'ammonium",
    "liquide amniotique",
    "protéine animale hydrolysée ampd isotérique",
    "anchois",
    "os d'animaux",
    "acides aminés de collagène animal",
    "graisse animale",
    "graisses et huiles animales",
    "poils d'animaux",
    "acides aminés de kératine animale",
    "huile animale",
    "placenta animal",
    "dérivé de protéine animale",
    "extrait de tissu animal",
    "acide arachidonique",
    "proprionate d'arachidyle",
    "acide aspartique",
    "astrakan",
    "lard dorsal",
    "basse",
    "alcool batylique",
    "isostéarate de batyle",
    "ours",
    "pollen d'abeille",
    "produits de l'abeille",
    "boeuf",
    "coeur de boeuf",
    "foie de boeuf",
    "langue de bœuf",
    "cire d'abeille",
    "cire d'abeille en nid d'abeille",
    "bacon de poitrine",
    "protéine animale hydrolysée au benzyltrimonium",
    "biotine vitamine h vitamine b facteur",
    "sang",
    "fractionnement du plasma sanguin",
    "langue de sang",
    "soies de sanglier",
    "jambon cuit",
    "cendre d'os",
    "charbon d'os",
    "noir d'os",
    "terre d'os",
    "poudre d'os",
    "phosphate d'os",
    "soupe d'os",
    "os/farine d'os",
    "bonite",
    "albumine de sérum bovin",
    "extrait de cerveau",
    "bacon de petit-déjeuner",
    "buffle",
    "lait de buffle",
    "viande de brousse",
    "beurre",
    "graisse de beurre",
    "matières solides du beurre",
    "babeurre",
    "babeurre en poudre",
    "huile de piscine c30-46",
    "calmar",
    "calciférol",
    "caséinate de calcium",
    "foie de veau",
    "peau de veau",
    "extrait de peau de veau",
    "lait de chamelle",
    "bacon canadien",
    "teinture de cantharides",
    "oxyde de caprylamine",
    "acide caprylique",
    "triglycéride caprylique",
    "carmin",
    "carmin cochineal acide carminique",
    "carmin/acide carminique",
    "carmin : cochenille. acide carminique",
    "carminique",
    "acide carminique",
    "carotène provitamine a bêta carotène",
    "carpe",
    "caséine",
    "caséinate de caséine, caséinate de sodium",
    "caséinate",
    "caséinogène",
    "cachemire",
    "castor",
    "castoréum",
    "poisson-chat",
    "catharidine",
    "cérébrosides",
    "certains additifs",
    "alcool cétylique",
    "lactate de cétyle",
    "myristate de cétyle",
    "palmitate de cétyle",
    "fromage",
    "poulet",
    "poitrine de poulet",
    "foie de poulet",
    "pain de poulet",
    "jambon fumé",
    "chitine",
    "cholécalciférol",
    "cholestérine",
    "cholestérol",
    "bitartrate de choline",
    "chondroïtine",
    "jambon haché",
    "chymotrypsine",
    "civette",
    "beurre clarifié",
    "crème caillée",
    "morue",
    "huile de foie de morue",
    "charcuterie",
    "collagène",
    "hydrolysat de collagène",
    "colorants",
    "lait condensé",
    "glaçage de confiseur",
    "viandes cuites",
    "corail",
    "poule de cornouailles",
    "cortico stéroïde",
    "corticostéroïde",
    "cortisone corticostéroïde",
    "cortisone : voir cortico stéroïde.",
    "fromage blanc",
    // netherlands 
    "acetaat",
    "geacetyleerde gehydrogeneerde reuzelglyceride",
    "geacetyleerde lanoline",
    "geacetyleerde lanolinealcohol",
    "geacetyleerd lanoline-ricinoleaat",
    "geacetyleerde talg",
    "zuur",
    "acidophilus-melk",
    "bijnieren van vee",
    "bijnieren van varkens",
    "bijnieren van schapen",
    "nageboorte",
    "eiwit",
    "alifatische alcohol",
    "krokodillenhuid",
    "alfa-hydroxyzuren",
    "ambergrijs",
    "aminiuccinaatzuur",
    "aminozuren",
    "aminosuccinaatzuur",
    "ammoniumcaseïnaat",
    "ammonium gehydrolyseerd eiwit",
    "vruchtwater",
    "ampd isoterisch gehydrolyseerd dierlijk eiwit",
    "ansjovis",
    "dierlijke botten",
    "dierlijke collageen aminozuren",
    "dierlijk vet",
    "dierlijke vetten en oliën",
    "dierenhaar",
    "dierlijke keratine aminozuren",
    "dierlijke olie",
    "dierlijke placenta",
    "dierlijk eiwitderivaat",
    "dierlijk weefselextract",
    "arachidonzuur",
    "arachidylpropionaat",
    "asparaginezuur",
    "rug spek",
    "rug vet",
    "spek",
    "bas",
    "batylalcohol",
    "batylisostearaat",
    "beer",
    "bijenpollen",
    "bijenproducten",
    "rundvlees",
    "runderhart",
    "runderlever",
    "rundertong",
    "bijenwas",
    "bijenwas honingraat",
    "buikspek",
    "benzyltrimonium gehydrolyseerd dierlijk eiwit",
    "biotine vitamine h vitamine b factor",
    "bizon",
    "bloed",
    "bloedplasma fractionering",
    "bloed tong",
    "zwijnenhaar",
    "gekookte ham",
    "beenderen",
    "bottenkool",
    "beenderkool (kool)/beenzwart",
    "beenderen houtskool",
    "beenderen aarde",
    "beendermeel",
    "botfosfaat",
    "bottensoep",
    "beenzwart",
    "bovine serum albumine",
    "hersenextract",
    "braadworst",
    "spierkracht",
    "ontbijtspek",
    "haar",
    "brueworst",
    "buffel",
    "buffelmelk",
    "bosvlees",
    "boter",
    "botervet",
    "boter vaste stoffen",
    "karnemelk",
    "karnemelkpoeder",
    "c30-46 visolie",
    "calamares",
    "calciumcaseïnaat",
    "kalfslever",
    "kalfsleer",
    "kalfsleer extract",
    "kamelenmelk",
    "canadees spek",
    "canthariden tinctuur",
    "capryl betaïne",
    "caprylamineoxide",
    "caprylzuur",
    "capryltriglyceride",
    "kariboe",
    "karmijn",
    "karmijn cochenille karmijnzuur",
    "karmijn/karmijnzuur",
    "karmijn: cochenille. karmijnzuur",
    "karmijnzuur",
    "caroteen provitamine een beta-caroteen",
    "karper",
    "caseïne",
    "caseïne caseïnaat natrium caseïnaat",
    "caseïnaat",
    "caseïnogeen",
    "kasjmier",
    "meerval",
    "kaviaar(e)",
    "cerebrosiden",
    "bepaalde toevoegingen",
    "cetylalcohol",
    "cetyllactaat",
    "cetylmyristaat",
    "cetylpalmitaat",
    "gemzen",
    "kaas",
    "kip",
    "kipfilet",
    "kippenlever",
    "kippenbrood",
    "gesnipperde ham",
    "cholesterine",
    "choline bitartraat",
    "gehakte ham",
    "geklaarde boter",
    "slagroom",
    "kabeljauw",
    "kabeljauwleverolie",
    "vleeswaren",
    "collageen",
    "collageenhydrolysaat",
    "kleuren kleurstoffen",
    "gecondenseerde melk",
    "banketbakkers glazuur",
    "gekookt vlees",
    "koraal",
    "cornish wild kip",
    "corticosteroïde",
    "cortison",
    "cortison corticosteroïde",
    "cortison: zie corticosteroïden.",
    "kwark",
    "krab",
    "krabvlees",
    "kreeft",
    "rivierkreeft",
    "room",
    "schaaldieren",
    "wrongel",
    "vla",
    "cysteïne, l-vorm",
    "donker vlees",
    "dea-oleth-10 fosfaat",
    "hert",
    "hertenvlees",
    "ontsuikerde wei",
    "gedemineraliseerde wei",
    "desoxyribonucleïnezuur",
    "desamido dierlijk collageen",
    "desamidocollageen",
    "dicapryloylcystine",
    "diethyleentricaseïnamide",
    "diglyceriden",
    "dihydrocholesterol octyledecanoaat",
    "gedihydrogeneerde talgbenzyloniumchloride",
    "gedihydrogeneerde talgmethylamine",
    "gedihydrogeneerd talgftalaat",
    "dihydroxyethyltalkamineoxide",
    "dimethylgehydrogeneerde talgamine",
    "dimethylstearamine",
    "dimethyltallowamine",
    "dinatriumgehydrogeneerd talgglutamaat",
    "dinatrium tallamido mea-sulfosuccinaat",
    "dinatrium talgaminodipropionaat",
    "ditallowdimoniumchloride",
    "omlaag",
    "gedroogde karnemelk",
    "gedroogd eigeel",
    "droge melkbestanddelen",
    "droge volle melk",
    "eend",
    "eendenspek",
    "eenden lever",
    "duodenumstoffen",
    "hollands brood",
    "kleurstoffen",
    "eetbaar botfosfaat",
    "ei-albumine",
    "ei-albumine/albumine",
    "eierolie",
    "eierpoeder",
    "ei-eiwit",
    "eiwitten",
    "eigeel",
    "eigeel extract",
    "eidooiers",
    "eieren",
    "elastine",
    "elandenbacon",
    "embryo-extract",
    "emu-olie",
    "epiderm olie r",
    "oestradiol",
    "oestradiolbenzoaat",
    "oestrogeen",
    "oestrogeen estradiol",
    "oestrogeen/oestradiol",
    "oestron",
    "ethylester van gehydrolyseerd dierlijk eiwit",
    "ethylmorrhuatelipineaat",
    "ethylarachidonaat",
    "ethyleen gedehydrogeneerd talgamide",
    "verdampte melk",
    "ooiemelk",
    "vetvrije melk",
    "vetvrije yoghurt",
    "vetten",
    "vetzuren",
    "fd en c kleuren",
    "veren",
    "voelde",
    "gefermenteerde kamelenmelk",
    "gefermenteerde room",
    "gefermenteerde melk",
    "vis",
    "visglyceriden",
    "vissenlever",
    "visleverolie",
    "vissenlevers",
    "visolie",
    "vissaus",
    "vissenschubben",
    "fletan olie",
    "vacht",
    "gelatinegel",
    "gelatine)",
    "gelbworst",
    "ghe",
    "maag",
    "glucose-tyrosinase",
    "glucuronzuur",
    "glutaminezuur",
    "glyceriden",
    "glycerine glycerol",
    "glyceryllanolaat",
    "glycerylen",
    "glycogeen",
    "geit",
    "geitenkaas",
    "geitenmelk",
    "ganzen isolerende veren",
    "ganzenlever",
    "gehakt",
    "hoen",
    "guanine parel essentie",
    "guanine/parelessence",
    "guinea kip",
    "zigeunerbacon",
    "schelvis",
    "haar van varkens",
    "heilbot",
    "ham en kaasbrood",
    "hoofd kaas",
    "zich verstoppen",
    "lijm verbergen",
    "gehomogeniseerde melk",
    "honing",
    "honingraat",
    "paard",
    "paardenhaar",
    "paardenvlees",
    "hotdog",
    "menselijk placenta-eiwit",
    "menselijk navelstrengextract",
    "hyaluronzuur",
    "gehydrolyseerd menselijk placenta-eiwit",
    "gehydrogeneerde dierlijke glyceride",
    "gehydrogeneerde ditalkamine",
    "gehydrogeneerde honing",
    "gehydrogeneerde laneth-20",
    "gehydrogeneerde laneth-25",
    "gehydrogeneerde laneth-5",
    "gehydrogeneerde lanoline",
    "gehydrogeneerde lanolinealcohol",
    "gehydrogeneerde reuzelglyceride",
    "gehydrogeneerde haaienleverolie",
    "gehydrogeneerd talgzuur",
    "gehydrogeneerde talg-betaïne",
    "gehydrogeneerde talgglyceride",
    "gehydrolyseerd dierlijk elastine",
    "gehydrolyseerde dierlijke keratine",
    "gehydrolyseerd dierlijk eiwit",
    "gehydrolyseerde caseïne",
    "gehydrolyseerde elastine",
    "gehydrolyseerde keratine",
    "gehydrolyseerd melkeiwit",
    "gehydrolyseerde zijde",
    "gehydroxyleerde lanoline",
    "softijs",
    "imidazolidinylureum",
    "insuline",
    "ijzercaseïnaat",
    "vislijm",
    "geïsobutyleerde lanoline",
    "isopropyllanolaat",
    "isopropylmyristaat",
    "isopropyl tallowatelsopropyl lanolaat",
    "isopropylpalmitaat",
    "isostearisch gehydrolyseerd dierlijk eiwit",
    "isostearoyl gehydrolyseerd dierlijk eiwit",
    "wang",
    "kangoeroe",
    "keratine",
    "keratineaminozuren",
    "l-cysteïne",
    "l-vorm",
    "l-vorm: zie cysteïne.",
    "l-melkzuur",
    "melk met verlaagd lactosegehalte",
    "lactalbumine",
    "melkgisten",
    "melkzuur",
    "lactoferrine",
    "lactoglobuline",
    "lactosevrije melk",
    "lam",
    "lamspek",
    "laan",
    "baan-10",
    "baan-11",
    "baan-12",
    "baan-13",
    "baan-14",
    "baan-15",
    "baan-16",
    "baan-17",
    "laan-18",
    "baan-19",
    "baan-20",
    "baan-21",
    "baan-22",
    "baan-23",
    "baan-24",
    "baan-25",
    "baan-26",
    "baan-27",
    "baan-28",
    "baan-29",
    "baan-30",
    "laan-31",
    "baan-32",
    "baan-33",
    "baan-34",
    "baan-35",
    "baan-36",
    "baan-37",
    "baan-38",
    "baan-39",
    "baan-40",
    "baan-5",
    "baan-6",
    "baan-7",
    "baan-8",
    "baan-9",
    "laneth-9 acetaat",
    "laneth10 acetaat",
    "lanogeen",
    "lanoïnamidedea",
    "lanoline",
    "lanoline zuur",
    "lanolinezuur: zie lanoline.",
    "lanoline alcohol",
    "lanoline alcoholen",
    "lanolinealcoholen: zie lanoline.",
    "lanoline lanolinezuren wolvet wolwas",
    "lanoline-linoleaat",
    "lanoline olie",
    "lanolinericinoleaat",
    "lanolinewas",
    "lanoline(e)",
    "lanoline: lanolinezuur",
    "lanosterol: zie lanoline.",
    "lanosterolen",
    "vet",
    "reuzel glyceride",
    "lauroyl gehydrolyseerd dierlijk eiwit",
    "leer",
    "leer suède kalfsleer schapenleer kalverhuid andere huidtypes",
    "lecithine cholinebitartraat",
    "linolzuur",
    "lipiden",
    "lipiden lipiden",
    "lever",
    "leverextract",
    "leverworst",
    "melk met weinig vet",
    "magere yoghurt",
    "maanspons",
    "lunchbrood",
    "lunchvlees",
    "makreel",
    "magnesiumcaseïnaat",
    "gemoute melk",
    "zoogdierextract",
    "zeeolie",
    "mergsoep",
    "mayonaise",
    "mea-gehydrolyseerde dierlijke eiwitten",
    "vlees",
    "gehaktbrood",
    "gehaktbal",
    "mechanisch gescheiden kip",
    "melk",
    "melkchocolade",
    "melkderivaat",
    "melk van zoogdieren",
    "melk proteïnen",
    "melkhuid",
    "melksuiker",
    "melk vet",
    "melkpoeder",
    "rundergehakt",
    "nertsolie",
    "minkamidopropyldiethylamine",
    "weekdieren schelpdieren",
    "zeeduivel",
    "mono- en diglyceriden",
    "monoglyceriden glyceriden",
    "monoglyceriden glyceriden (zie glycerine)",
    "eland",
    "mosbunkerolie",
    "matje",
    "spierextract",
    "muskus",
    "muskus (olie)",
    "muskus ambrette",
    "mossel",
    "mosselen",
    "schaap",
    "myristalethersulfaat",
    "myristaatzuur",
    "myristinezuur",
    "myristoyl gehydrolyseerd dierlijk eiwit",
    "myristylen",
    "natuurlijke botersmaak",
    "natuurlijke smaakstoffen",
    "natuurlijk rood 4",
    "natuurlijke bronnen",
    "nek",
    "magere melk",
    "notitie:",
    "noga",
    "nucleïnezuren",
    "octyldodecanol",
    "oliën",
    "oleamidopropyldimethylamine gehydrolyseerd dierlijk eiwit",
    "oliezuur",
    "oleoïsche olie",
    "oleoyl gehydrolyseerd dierlijk eiwit",
    "olieten",
    "oleylarachidaat",
    "oleyl lanolaat",
    "oleylmyristaat",
    "oleyloleaat",
    "oleylstearaat",
    "oleylalcoholocenol",
    "omega-3 vetzuren",
    "orgaanvlees",
    "organen",
    "struisvogel",
    "ovalbumine",
    "eierstokextract",
    "ossengal",
    "oester",
    "palmitaat",
    "palmitinezuur",
    "palmitoyl gehydrolyseerd melkeiwit",
    "palmitoyl gehydrolyseerd dierlijk eiwit",
    "panthenol dexpanthenol vitamine b-complex factor provitamine b-5",
    "paracaseïne",
    "patrijs",
    "gepasteuriseerde melk",
    "parel",
    "parel essentie",
    "pentahydrosqualeen",
    "pepsine",
    "perhydrosqualeen",
    "farmaceutisch glazuur",
    "fazant",
    "picknick schouder",
    "varkensleer extract",
    "placenta placenta polypeptiden eiwit nageboorte",
    "placenta-polypeptiden-eiwit",
    "placentale enzymen",
    "placenta extract",
    "placentaal eiwit",
    "schol",
    "pogy olie",
    "koolvis",
    "poltethyleencetylether",
    "polyglyceryl-2lanolin alcoholether",
    "polypeptiden",
    "polypeptiden eiwit",
    "polysorbaten",
    "polytetyleenglycerol/glycol/peg",
    "varkens alvleesklier",
    "varkensvlees",
    "varkensvet",
    "varkensbroodje",
    "kaliumcaseïnaat",
    "kaliumtallowaat",
    "kaliumundecylenoyl gehydrolyseerd dierlijk eiwit",
    "gevogelte",
    "ppg-12-peg-50 lanoline",
    "ppg-2,-5, -10. -20, -30 lanolinealcoholethers",
    "ppg-30 lanoline-ether",
    "garnaal",
    "pregnenolonacetaat",
    "ongerept",
    "provitamine a",
    "provitamine b-5",
    "provitamine d-2",
    "purcelline olie syn",
    "kwartel",
    "konijn",
    "rood vlees",
    "stremsel",
    "stremsel caseïne",
    "stremsel rennine",
    "rennine",
    "harsachtig glazuur",
    "reticuline",
    "ribonucleïnezuur",
    "rna ribonucleïnezuur",
    "rosbief",
    "geroosterd varken",
    "kuit",
    "koninklijke gelei",
    "sabel",
    "marterborstels",
    "sacharidehydrolysaat",
    "sacharide-isomeraat",
    "zalm",
    "worst",
    "worsten",
    "schelp",
    "coquilles",
    "zee spons",
    "zeeschildpad olie",
    "zeespons",
    "serum albumine",
    "serumeiwitten",
    "haaienleverolie",
    "schapenmelk",
    "schapenvacht",
    "schellak",
    "schellak harsachtig glazuur",
    "schellakwas",
    "schouder",
    "garnalen",
    "zijspek",
    "zijde",
    "zijde aminozuren",
    "zijdepoeder",
    "zijde zijde poeder",
    "spek spek",
    "roken",
    "slak",
    "slakken",
    "slang",
    "natrium / thee-lauroyl gehydrolyseerd dierlijk eiwit",
    "natrium / thee-undecylenoyl gehydrolyseerd dierlijk eiwit",
    "natriumcaseïnaat",
    "natrium-kokos-gehydrolyseerd dierlijk eiwit",
    "natrium soja gehydrolyseerd dierlijk eiwit",
    "natriumtalksulfaat",
    "natriumtallowaat",
    "natrium undecylenaat",
    "natriumsteroyllactylaat",
    "oplosbaar collageen",
    "zure room",
    "zure melk",
    "zure melkbestanddelen",
    "soja-hydroxyethylimidazoline",
    "zaadolie",
    "potvisdarmen",
    "spermaceticetylpalmitaatspermaolie",
    "milt extract",
    "spons (luna en zee)",
    "squalaan",
    "squaleen",
    "inktvis",
    "eekhoorn",
    "stearamineoxide",
    "stearaten",
    "stearinezuur",
    "stearinehydrazide",
    "stearine",
    "stearoxytrimethylsilaan",
    "stearoyllactylzuur",
    "stearylacetaat",
    "stearylalcoholsterolen",
    "stearylbetaïne",
    "stearylcaprylaat",
    "stearylcitraat",
    "stearylglycyrrhetinaat",
    "stearylheptanoaat",
    "stearylimidazoline",
    "stearyl octanoaat",
    "stearylstearaat",
    "stearyldimethylamine",
    "steroïden sterolen",
    "sterolen",
    "stoofvlees",
    "gestreepte bacon",
    "suède",
    "zoete melkwei",
    "zoete wei",
    "zwezeriken",
    "gezoete gecondenseerde melk",
    "zwaardvis",
    "talkzuur",
    "talkamide",
    "talkamine",
    "talkamineoxide",
    "talkvetalcohol",
    "talkglyceriden",
    "talkhydroxyethal-imidazoline",
    "talk-imidazoline",
    "talk talg vetalcohol stearinezuur",
    "talktrioniumchloride - talg",
    "tallowamidopropylamineoxide",
    "tallowmide dea en mea",
    "talgmidopropylhydroxysultaine",
    "talkminopropylamine",
    "talgmphoaceet",
    "thee-abietoyl gehydrolyseerd dierlijk eiwit",
    "thee-kokos gehydrolyseerd dierlijk eiwit",
    "tea-lauroyl dierlijke collageen aminozuren",
    "tea-lauroyl dierlijke keratine aminozuren",
    "tea-myristol gehydrolyseerd dierlijk eiwit",
    "thee-undecylenoyl gehydrolyseerd dierlijk eiwit",
    "testikelextract",
    "thüringer worst",
    "tong",
    "triethonium gehydrolyseerd dierlijk eiwit ethosulfaat",
    "trilaneth-4fosfaat",
    "pens",
    "triterpeenalcoholen",
    "forel",
    "trypsine",
    "tonijn",
    "kalkoen",
    "turkse bacon",
    "kalkoenfilet",
    "schildpad",
    "schildpad olie",
    "niet-gehomogeniseerde melk",
    "ureum",
    "ureumcarbamide",
    "urinezuur",
    "urinezuur van koeien",
    "kalfsvlees",
    "kalfsbrood",
    "vitamine a",
    "vitamine b-complexfactor",
    "vitamine d ergocalciferol vitamine d",
    "vitamine d3",
    "vitamine h",
    "vitamine",
    "vitamineb-factor",
    "wei",
    "weipoeder",
    "wei-eiwit",
    "opgeklopte topping",
    "wit vlees",
    "volle melk",
    "volle melk yoghurt",
    "wild zwijn",
    "wild vlees",
    "wol",
    "wolvet",
    "wolwas",
    "wolwasalcoholen",
    "zinkcaseïnaat",
    "zink gehydrolyseerd dierlijk eiwit",
    // italian
     "abalone",
    "acciuga",
    "acciughe",
    "acetato",
    "acidi grassi omega-3",
    "acidi grassi",
    "acidi nucleici",
    "acido aminiuccinato",
    "acido aminosuccinato",
    "acido arachidonico",
    "acido aspartico",
    "acido caprilico",
    "acido carminico cocciniglia del carminio",
    "acido carminico",
    "acido desossiribonucleico",
    "acido di sego idrogenato",
    "acido di sego",
    "acido glucuronico",
    "acido glutammico",
    "acido ialuronico",
    "acido l-lattico",
    "acido lanolina: vedi lanolina.",
    "acido lanolina",
    "acido lattico",
    "acido linoleico",
    "acido miristato",
    "acido miristico",
    "acido oleico",
    "acido palmitico",
    "acido ribonucleico",
    "acido rna ribonucleico",
    "acido stearico",
    "acido stearoil-lattilico",
    "acido urico di mucche",
    "acido urico",
    "acido",
    "adrenalina",
    "affettati",
    "agnello",
    "alanina",
    "albume d'uovo / albumina",
    "albume d'uovo",
    "albume",
    "albumi",
    "albumina sierica bovina",
    "albumina",
    "alcoli di lana di cera",
    "alcoli di lanolina: vedi lanolina.",
    "alcoli di lanolina",
    "alcoli triterpenici",
    "alcool acetato di lanolina",
    "alcool alifatico",
    "alcool batilico",
    "alcool cetilico",
    "alcool di lanolina",
    "alcool grasso sego",
    "alcool idrogenato di lanolina",
    "alcuni additivi",
    "alfa-idrossiacidi",
    "allantoina",
    "alligatore",
    "ambra grigia",
    "amilasi",
    "aminoacidi cheratinici animali",
    "aminoacidi",
    "ammina di ditallow idrogenata",
    "amminoacidi cheratinici animali tea-lauroilici",
    "amminoacidi di collagene animale di tè-lauroile",
    "amminoacidi di collagene animale",
    "amminoacidi di seta",
    "ampd proteina animale idrolizzata isoterica",
    "anatra",
    "animelle",
    "arachidil proprionato",
    "aragosta",
    "aroma naturale di burro",
    "aromi naturali",
    "arrosto di manzo",
    "basso",
    "batil isostearato",
    "betaina di sego idrogenata",
    "bile di bue",
    "bisonte",
    "bistecca stufata",
    "bistecca",
    "bitartrato di colina",
    "bone char (carbone) / boneblack",
    "bottarga",
    "bufala",
    "burro chiarificato",
    "burro di latte",
    "burro",
    "cagliata",
    "caglio",
    "calamaro",
    "calciferolo",
    "camoscio",
    "canguro",
    "capra",
    "carbone osseo",
    "caribù",
    "carmine / acido carminico",
    "carmine: cocciniglia. acido carminico",
    "carminico",
    "carminio",
    "carne bianca",
    "carne di animali selvatici",
    "carne di cervo",
    "carne di manzo macinata",
    "carne di organo",
    "carne in scatola",
    "carne macinata",
    "carne rossa",
    "carne scura",
    "carne selvatica",
    "carne",
    "carni cotte",
    "carni d'organo",
    "carpa",
    "caseina di caglio",
    "caseina idrolizzata",
    "caseina",
    "caseinato caseinato di sodio caseinato",
    "caseinato di ammonio",
    "caseinato di calcio",
    "caseinato di ferro",
    "caseinato di magnesio",
    "caseinato di potassio",
    "caseinato di sodio",
    "caseinato di zinco",
    "caseinato",
    "cavallo",
    "caviar (e)",
    "cenere ossea",
    "cera d'api a nido d'ape",
    "cera d'api",
    "cera di gommalacca",
    "cera di lana",
    "cera di lanolina",
    "cerebrosidi",
    "cervo",
    "cetil lattato",
    "cetil miristato",
    "cetil palmitato",
    "cheratina animale idrolizzata",
    "cheratina idrolizzata",
    "cheratina",
    "cheratinaminoacidi",
    "chimotripsina",
    "chitina",
    "chitosano",
    "cinghiale",
    "cisteina, forma a l",
    "cistina",
    "cocciniglia",
    "colecalciferolo",
    "colesterina",
    "colesterolo",
    "colla di pesce",
    "collagene solubile",
    "collagene",
    "collo",
    "coloranti",
    "colori coloranti",
    "colori fd e c",
    "condroitina",
    "coniglio",
    "corallo",
    "cortico steroide",
    "corticosteroide cortisone",
    "corticosteroide",
    "cortisone: vedi cortico steroide.",
    "cozza",
    "cozze",
    "crema fermentata",
    "crema pasticciera",
    "crema pesante",
    "crema",
    "crine di cavallo",
    "crostacei",
    "cuore di manzo",
    "dea-olet-10 fosfato",
    "derivato del latte",
    "derivato proteico animale",
    "desamido collagene animale",
    "dexpantenolo",
    "dietilene tricaseinamide",
    "digliceridi",
    "dihydrocholesterol otttyledecanoate",
    "diidrossietil sego ossido di ammina",
    "dimetil idrogenato tallowamina",
    "dimetil stearamina",
    "dimetil tallowamina",
    "disodio tallamido mea-solfosuccinato",
    "dolce siero di latte",
    "eglefino",
    "elastina animale idrolizzata",
    "elastina idrolizzata",
    "elastina",
    "enzimi placentare",
    "ergocalciferolo",
    "ergosterolo",
    "essenza di perle",
    "essenza di perle di guanina",
    "estere etilico di proteine ​​animali idrolizzate",
    "estradiolo benzoato",
    "estradiolo",
    "estratto di cervello",
    "estratto di embrioni",
    "estratto di fegato",
    "estratto di mammiferi",
    "estratto di milza",
    "estratto di pelle di maiale",
    "estratto di pelle di vitello",
    "estratto di tessuto animale",
    "estratto di tuorlo d'uovo",
    "estratto muscolare",
    "estratto ombelicale umano",
    "estratto ovarico",
    "estratto placentare",
    "estratto testicolare",
    "estrogeni",
    "estrogeno / estradiolo",
    "estrogeno estradiolo",
    "etere alcolico poligliceril-2lanolinico",
    "etere di lanolina ppg-30",
    "etere solfato miristico",
    "etil morrhuatelipineate",
    "etosolfato di proteine ​​animali idrolizzato trietonio",
    "fagiano",
    "farina d'ossa",
    "fattore complesso vitaminico b",
    "fattore di vitamina b della vitamina h della biotina",
    "fattore vitaminico",
    "favo",
    "fegatini di pesce",
    "fegato d'anatra",
    "fegato d'oca",
    "fegato di manzo",
    "fegato di pesce",
    "fegato di pollo",
    "fegato di vitello",
    "fegato",
    "fiocchi di latte",
    "fonti naturali",
    "formaggio di capra",
    "formaggio",
    "fosfato osseo commestibile",
    "fosfato osseo",
    "frazionamento del plasma sanguigno",
    "ftalato di sego diidrogenato",
    "gallina faraona",
    "gallina selvatica della cornovaglia",
    "gamberetto",
    "gamberi",
    "gambero",
    "gelatina",
    "gelato",
    "ghiandole surrenali",
    "giù",
    "glassa di pasticceri",
    "glassa farmaceutica",
    "glassa resinosa gommalacca",
    "gliceride animale idrogenato",
    "gliceride di lardo idrogenato acetilato",
    "gliceride di lardo idrogenato",
    "gliceride di lardo",
    "gliceride di sego idrogenato",
    "gliceridi di pesce",
    "gliceridi di sego",
    "gliceridi",
    "gliceril lanolato",
    "glicerina glicerolo",
    "glicerolo",
    "glicogeno",
    "glucosamina",
    "glucosio tirosinasi",
    "glutammato di sodio idrogenato disodico",
    "gommalacca",
    "granchio",
    "grassi e oli animali",
    "grassi",
    "grasso alla schiena",
    "grasso animale",
    "grasso di burro",
    "grasso di lana",
    "guancia",
    "guanina",
    "guanina / essenza di perle",
    "idrazide stearica",
    "idrocortisone",
    "idrogenato lanet-20",
    "idrogenato lanet-5",
    "idrolizzato di collagene",
    "idrolizzato di saccaride",
    "idrossietil imidazolina di soia",
    "insulina",
    "intestini di capodoglio",
    "involtino di maiale",
    "isomerato di saccaride",
    "isopropil lanolato",
    "isopropil miristato",
    "l-cisteina",
    "l-form: vedi cisteina.",
    "l-forma",
    "lana",
    "lanet-9 acetato",
    "lanet10 acetato",
    "laneth-25 idrogenato",
    "lanolina (e)",
    "lanolina acetilata",
    "lanolina idrogenata",
    "lanolina idrossilata",
    "lanolina isobutilata",
    "lanolina lanolina acido lana lana grassa cera",
    "lanolina ppg-12-peg-50",
    "lanolina ricinoleata",
    "lanolina: acido lanolinico",
    "lanolina",
    "lanosterolo: vedi lanolina.",
    "lanosterolo",
    "lardo",
    "latte a ridotto contenuto di grassi",
    "latte a ridotto contenuto di lacotse",
    "latte acido",
    "latte acidofilo",
    "latte al cioccolato",
    "latte condensato dolcificato",
    "latte condensato",
    "latte di bufala",
    "latte di cammello fermentato",
    "latte di cammello",
    "latte di capra",
    "latte di mammiferi",
    "latte di pecora",
    "latte e malto in polvere",
    "latte evaporato",
    "latte fermentato",
    "latte grasso",
    "latte in polvere",
    "latte intero secco",
    "latte intero",
    "latte magro",
    "latte non omogeneizzato",
    "latte omogeneizzato",
    "latte pastorizzato",
    "latte scremato",
    "latte senza lattosio",
    "latte",
    "latticello essiccato",
    "latticello in polvere",
    "lattoalbumina",
    "lattoferrina",
    "lattoglobulina",
    "lattosio",
    "lattulosio",
    "lecitina colinbitartrato",
    "leucina",
    "lieviti lattici",
    "lingua di manzo",
    "lingua di sangue",
    "lingua",
    "linoleato di lanolina",
    "lipasi",
    "lipidi lipidici",
    "lipidi",
    "liquido amniotico",
    "lisina",
    "lumaca",
    "lumache",
    "maiale arrosto",
    "maiale grasso",
    "maiale",
    "maionese",
    "manzo",
    "merluzzo",
    "metilammina di sego diidrogenata",
    "metionina",
    "miele idrogenato",
    "miele",
    "minkamidopropil dietilammina",
    "molluschi molluschi",
    "mono e di gliceridi",
    "monogliceridi gliceridi (vedi glicerina)",
    "monogliceridi gliceridi",
    "montone",
    "muschio",
    "nascondere",
    "nascondi colla",
    "nota:",
    "oca",
    "oleil arachidato",
    "oleil betatina",
    "oleil imidazolina",
    "oleil lanolato",
    "oleil miristato",
    "oleil oleato",
    "oleil stearato",
    "oleostearina",
    "oli",
    "olio animale",
    "olio d'uovo",
    "olio di fegato di merluzzo",
    "olio di fegato di pesce",
    "olio di fegato di squalo idrogenato",
    "olio di fegato di squalo",
    "olio di fletan",
    "olio di lanolina",
    "olio di mossbunker",
    "olio di pesce",
    "olio di pogy",
    "olio di sperma di palmitato di spermaceticetile",
    "olio di sperma",
    "olio di tartaruga marina",
    "olio di tartaruga",
    "olio di visone",
    "olio marino",
    "olio oleoico",
    "organi",
    "orso",
    "ossa di animali",
    "ossido di caprylamine",
    "ossido di stearamina",
    "osso / ossa",
    "ostrica",
    "ottil dodecanolo",
    "ovalbumina",
    "pagnotta di luncehon",
    "pagnotta di prosciutto e formaggio",
    "pagnotta di vitello",
    "pagnotta olandese",
    "palmitammide",
    "palmitato di isopropile",
    "palmitato",
    "pancetta affumicata",
    "pancetta alce",
    "pancetta canadese",
    "pancetta d'anatra",
    "pancetta di agnello",
    "pancetta di tacchino",
    "pancetta laterale",
    "pancetta per la colazione",
    "pancetta striata",
    "pancetta zingara",
    "pancreas suino",
    "panna acida",
    "panna montata",
    "panna rappresa",
    "pantenolo despantenolo vitamina b-complesso fattore provitamina b-5",
    "pappa reale",
    "paracaseina",
    "passera di mare",
    "pecora",
    "peli di animali",
    "pelle di alligatore",
    "pelle di latte",
    "pelle di vitello scamosciato pelle di pecora pelle di alligatore altri tipi di pelle",
    "pelle di vitello",
    "pelle",
    "pelliccia",
    "pelo di maiale",
    "pepsina",
    "perla",
    "pernice",
    "pesce gatto",
    "pesce spada",
    "pesce",
    "pettine",
    "petto di pollo",
    "petto di tacchino",
    "piccioncino",
    "piume isolanti d'oca",
    "piume",
    "placenta animale",
    "placenta placenta polipeptidi proteina post-parto",
    "poliglicerolo",
    "polipeptidi",
    "polisorbati",
    "politetilene glicerolo / glicole / piolo",
    "pollame",
    "polline d'api",
    "pollo separato meccanicamente",
    "pollo",
    "polpa di granchio",
    "polpetta",
    "polpettone",
    "polpo",
    "poltetilene cetiletere",
    "polvere di seta",
    "ppg-2, -5, -10. -20, -30 eteri di alcol lanolinale",
    "pranzi di carne",
    "pregnenolone acetato",
    "pristano",
    "prodotti delle api",
    "propoli",
    "prosciutto affumicato",
    "prosciutto cotto",
    "prosciutto crudo",
    "prosciutto tritato",
    "proteina animale idrolizzata benziltrimonium",
    "proteina animale idrolizzata con oleamidopropil dimetilammina",
    "proteina animale idrolizzata con oleoile",
    "proteina animale idrolizzata isostearica",
    "proteina animale idrolizzata isostearoil",
    "proteina animale idrolizzata miristilica",
    "proteina palmitoil idrolizzata-animale",
    "proteina placentare umana idrata",
    "proteina placentare umana",
    "proteina placentare",
    "proteina polipeptidica della placenta",
    "proteina polipeptidica",
    "proteina tè-abietoil idrolizzata",
    "proteine ​​animali idrolizzate al tè e cocco",
    "proteine animali idrolizzate allo zinco",
    "proteine ​​animali idrolizzate con cocco",
    "proteine ​​animali idrolizzate con sodio / tè-lauroil",
    "proteine ​​animali idrolizzate con sodio / tè-undecilenoil",
    "proteine ​​animali idrolizzate con soia e sodio",
    "proteine ​​animali idrolizzate con tè e mirto",
    "proteine ​​animali idrolizzate con tè-undecilenoil",
    "proteine ​​animali idrolizzate con undecilenoil di potassio",
    "proteine ​​animali idrolizzate lauroil",
    "proteine ​​animali idrolizzate",
    "proteine ​​animali midrolizzate",
    "proteine ​​del latte idrolizzate palmitoil",
    "proteine ​​del latte idrolizzate",
    "proteine ​​del latte",
    "proteine del siero di latte",
    "proteine ​​del siero",
    "proteine ​​dell'uovo",
    "proteine ​​idrolizzate con ammonio",
    "provato",
    "provitamina b-5",
    "provitamina d-2",
    "quaglia",
    "rana pescatrice",
    "renina",
    "reticolina",
    "retinolo",
    "ricinoleato di lanolina acetilato",
    "rosso naturale 4",
    "salame",
    "salmone",
    "salsa di pesce",
    "salsicce",
    "salsiccia della turingia",
    "salsiccia di fegato",
    "salsiccia",
    "salumi",
    "sangue",
    "sardina",
    "scaloppine",
    "scoiattolo",
    "sego acetilato",
    "sego ammido",
    "sego ammina",
    "sego benzilmonio cloruro diidrogenato",
    "sego idrossietale imidazolina",
    "sego imidazolina",
    "sego ossido di ammina",
    "sego trimonio cloruro - sego",
    "sego, sego, alcool grasso, acido stearico",
    "sego",
    "serpente",
    "seta idrolizzata",
    "seta seta in polvere",
    "seta",
    "setola",
    "setole di cinghiale",
    "sgombro",
    "siero albumina",
    "siero demineralizzato",
    "siero di latte delattosato",
    "siero di latte dolce",
    "siero di latte in polvere",
    "siero",
    "smalto resinoso",
    "sodiosteroil lacilato",
    "solfato di sego di sodio",
    "solidi del latte acido",
    "solidi di burro",
    "solidi secchi del latte",
    "sostanze del duodeno",
    "spalla da picnic",
    "spalla",
    "spazzole di sabbia",
    "spugna (luna e mare)",
    "spugna di mare",
    "squalano",
    "squame di pesce",
    "stearammide",
    "stearati",
    "stearil acetato",
    "stearil betaina",
    "stearil caprilato",
    "stearil citrato",
    "stearil eptanoato",
    "stearil glicirretinato",
    "stearil imidazolina",
    "stearil ottanoato",
    "stearil stearato",
    "stearildimetilammina",
    "stearina",
    "steroidi steroli",
    "steroli con alcool stearilico",
    "steroli",
    "struzzo",
    "tacchino",
    "talco di potassio",
    "tallowamide deidrogenata di etilene",
    "tallowaminodipropionato di disodio",
    "tallowato di sodio",
    "tartaruga",
    "terra dell'osso",
    "testa in cassetta",
    "tintura di cantharides",
    "tirosina",
    "tonno",
    "topping topping",
    "torrone",
    "treonina",
    "trigliceride caprilico",
    "trippa",
    "tripsina",
    "trota",
    "tuorli d'uovo",
    "tuorlo d'uovo essiccato",
    "tuorlo d'uovo",
    "undecilenato di sodio",
    "uova",
    "uovo in polvere",
    "uovo",
    "urina",
    "ventriglio",
    "vitamina a",
    "vitamina d ergocalciferolo vitamina d",
    "vitamina d3",
    "vitamina h",
    "vitello",
    "yogurt a basso contenuto di grassi",
    "yogurt intero",
    "yogurt magro ridotto",
    "yogurt senza grassi",
    "zucchero del latte",
    "zuppa di midollo",
    "zuppa di ossa",
    // spanish
    "abulón",
    "glicérido de manteca hidrogenada acetilada",
    "lanolina acetilada",
    "alcohol de lanolina acetilado",
    "ricinoleato de lanolina acetilada",
    "sebo acetilado",
    "ácido",
    "leche acidófila",
    "suprarrenales de ganado",
    "suprarrenales de cerdo",
    "suprarrenales de las ovejas",
    "posparto",
    "albúmina",
    "alcohol alifático",
    "alantoína",
    "caimán",
    "piel de caimán",
    "alfa-hidroxiácidos",
    "ámbar gris",
    "ameracol",
    "ácido aminiuccinado",
    "aminoácidos",
    "ácido aminosuccinado",
    "caseinato de amonio",
    "proteína hidrolizada de amonio",
    "líquido amniótico",
    "proteína animal hidrolizada isotérica",
    "amilasa",
    "anchoas",
    "anchoa",
    "huesos de animales",
    "aminoácidos de colágeno animal",
    "grasa animal",
    "grasas y aceites animales",
    "pelo animal",
    "aminoácidos de queratina animal",
    "aceite animal",
    "derivado de proteína animal",
    "extracto de tejido animal",
    "ácido araquidónico",
    "ácido aspártico",
    "astracán",
    "tocino de espalda",
    "grasa dorsal",
    "tocino",
    "bajo",
    "alcohol batílico",
    "oso",
    "polen de abeja",
    "productos apícolas",
    "carne de vacuno",
    "corazón de vacuno",
    "hígado de buey",
    "lengua de vaca",
    "cera de abejas",
    "panal de cera de abeja",
    "panceta",
    "proteína animal hidrolizada de benziltrimonio",
    "biotina vitamina h factor b",
    "sangre",
    "fraccionamiento de plasma sanguíneo",
    "lengua de sangre",
    "cerdas de jabalí",
    "jamón cocido",
    "ceniza de hueso",
    "carbón de hueso",
    "carbón de hueso/negro",
    "tierra de huesos",
    "harina de huesos",
    "fosfato de hueso",
    "sopa de huesos",
    "hueso negro",
    "albúmina de suero bovino",
    "extracto de cerebro",
    "tocino de desayuno",
    "cerda",
    "búfalo",
    "leche de búfalo",
    "mantequilla",
    "grasa de mantequilla",
    "sólidos de mantequilla",
    "suero de leche",
    "suero de leche en polvo",
    "aceite piscino c30-46",
    "caseinato de calcio",
    "hígado de ternera",
    "piel de ternera",
    "extracto de piel de ternera",
    "leche de camello",
    "tocino canadiense",
    "tintura de cantáridas",
    "capril betaína",
    "óxido de caprilamina",
    "ácido caprílico",
    "triglicérido caprílico",
    "carbamida",
    "caribú",
    "carmín",
    "carmín cochinilla ácido carmínico",
    "carmín/ácido carmínico",
    "carmín: cochinilla. ácido carmínico",
    "carmínico",
    "ácido carmínico",
    "caroteno provitamina a beta caroteno",
    "caseína",
    "caseína caseinato de sodio",
    "caseinógeno",
    "cachemira",
    "ricino",
    "castóreo",
    "bagre",
    "cataridina",
    "cerebrósidos",
    "ciertos aditivos",
    "alcohol cetílico",
    "lactato de cetilo",
    "miristato de cetilo",
    "palmitato de cetilo",
    "gamuza",
    "queso",
    "pechuga de pollo",
    "hígado de pollo",
    "pan de pollo",
    "jamón picado",
    "quitina",
    "quitosano",
    "colecalciferol",
    "colesterol",
    "bitartrato de colina",
    "quimotripsina",
    "mantequilla clarificada",
    "crema coagulada",
    "cochinilla",
    "bacalao",
    "aceite de hígado de bacalao",
    "embutidos",
    "colágeno",
    "hidrolizado de colágeno",
    "colorantes",
    "leche condensada",
    "glaseado de confitería",
    "carnes cocidas",
    "corticoesteroide",
    "cortisona",
    "cortisona corticosteroide",
    "cortisona: véase corticoesteroide",
    "requesón",
    "cangrejo",
    "carne de cangrejo",
    "langosta",
    "cangrejo de río",
    "marisco crustáceo",
    "cuajada",
    "flan",
    "cisteína, forma-l",
    "carne oscura",
    "ciervo",
    "carne de ciervo",
    "suero delactosado",
    "carne delactosada",
    "suero desmineralizado",
    "ácido desoxirribonucleico",
    "colágeno animal desamidado",
    "desamidocolágeno",
    "dexpantenol",
    "dicapriloil cistina",
    "tricaseinamida de dietileno",
    "diglicéridos",
    "dihidrocolesterol",
    "octiledecanoato de dihidrocolesterol",
    "dihidrocolesterol-15",
    "dihidrocolesterol-30",
    "cloruro de bencilmonio de sebo dihidrogenado",
    "metilamina de sebo dihidrogenada",
    "ftalato de sebo dihidrogenado",
    "óxido de amina de sebo dihidroxilado",
    "dimetil hidrogenado de sebo",
    "dimetil estearamina",
    "dimetil seboamina",
    "glutamato disódico hidrogenado de sebo",
    "tallamido mea-sulfosuccinato disódico",
    "tallowaminodipropionato disódico",
    "cloruro de ditallowdimonium",
    "adn",
    "suero de leche seco",
    "yema de huevo seca",
    "sólidos lácteos secos",
    "leche entera seca",
    "pato",
    "tocino de pato",
    "hígado de pato",
    "sustancias del duodeno",
    "pan holandés",
    "tintes",
    "fosfato óseo comestible",
    "huevo",
    "albúmina de huevo",
    "albúmina de huevo/albúmina",
    "aceite de huevo",
    "huevo en polvo",
    "proteína de huevo",
    "clara de huevo",
    "yema de huevo",
    "extracto de yema de huevo",
    "yemas de huevo",
    "huevos",
    "tocino de alce",
    "extracto de embrión",
    "aceite de emú",
    "benzoato de estradiol",
    "estrógeno",
    "estrógeno estradiol",
    "estrógeno/estradiol",
    "estrona",
    "éster etílico de proteína animal hidrolizada",
    "morrhuatelipineato de etilo",
    "etillaracidonato",
    "etileno deshidrogenado de sebo",
    "leche evaporada",
    "leche de oveja",
    "leche sin grasa",
    "yogur sin grasa",
    "grasas",
    "ácidos grasos",
    "colores fd y c",
    "plumas",
    "fieltro",
    "leche de camello fermentada",
    "crema fermentada",
    "leche fermentada",
    "pescado",
    "glicéridos de pescado",
    "hígado de pescado",
    "aceite de hígado de pescado",
    "aceite de pescado",
    "salsa de pescado",
    "escamas de pescado",
    "aceite de fletán",
    "piel",
    "gelatina(e)",
    "mollejas",
    "glucosa tirosinasa",
    "ácido glucurónico",
    "ácido glutámico",
    "glicéridos",
    "glicerina glicerol",
    "glicerol",
    "glicerilos",
    "glicerina",
    "glicerina-26",
    "cabra",
    "queso de cabra",
    "leche de cabra",
    "ganso",
    "plumas aislantes de ganso",
    "hígado de ganso",
    "carne picada",
    "urogallo",
    "esencia de perla de guanina",
    "esencia de guanina/perla",
    "gallina de guinea",
    "tocino gitano",
    "abadejo",
    "pelo de cerdo",
    "fletán",
    "jamón",
    "pan de jamón y queso",
    "queso de cabeza",
    "crema de leche",
    "cuero",
    "pegamento para pieles",
    "leche homogeneizada",
    "miel",
    "panal",
    "caballo",
    "pelo de caballo",
    "carne de caballo",
    "perro caliente",
    "proteína de placenta humana",
    "extracto umbilical humano",
    "ácido hialurónico",
    "proteína placentaria humana hidrolizada",
    "hidrocortisona",
    "glicérido animal hidrogenado",
    "amina ditálica hidrogenada",
    "miel hidrogenada",
    "laneth-20 hidrogenado",
    "laneth-25 hidrogenado",
    "laneth-5 hidrogenado",
    "lanolina hidrogenada",
    "alcohol de lanolina hidrogenado",
    "glicérido de manteca de cerdo hidrogenado",
    "aceite de hígado de tiburón hidrogenado",
    "ácido de sebo hidrogenado",
    "betaína de sebo hidrogenada",
    "glicérido de sebo hidrogenado",
    "elastina animal hidrolizada",
    "queratina animal hidrolizada",
    "proteína animal hidrolizada",
    "caseína hidrolizada",
    "elastina hidrolizada",
    "queratina hidrolizada",
    "proteína de leche hidrolizada",
    "seda hidrolizada",
    "lanolina hidroxilada",
    "helado",
    "imidazolidinil urea",
    "caseinato de hierro",
    "vidrio iso",
    "lanolina isobutilada",
    "lanolato de isopropilo",
    "miristato de isopropilo",
    "lanolato de isopropilo de sebo",
    "isopropilpalmitato",
    "proteína animal hidrolizada isoesteárica",
    "proteína animal hidrolizada isoestearílica",
    "papada",
    "queratina",
    "queratinaminoácidos",
    "l-cisteína",
    "l-forma: véase cisteína",
    "ácido l-láctico",
    "leche reducida a la lactosa",
    "lactoalbúmina",
    "levaduras lácticas",
    "ácido láctico",
    "lactoferrina",
    "lactoglobulina",
    "lactosa",
    "leche sin lactosa",
    "lactulosa",
    "cordero",
    "tocino de cordero",
)
?>